# Generated by Django 5.2.17 on 2026-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('backdrop_path', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('duration', models.PositiveIntegerField(default=120, help_text='Duration in minutes')),
                ('language', models.CharField(default='English', max_length=50)),
                ('genres', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NOW_SHOWING', 'Now Showing'), ('COMING_SOON', 'Coming Soon')], default='NOW_SHOWING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
